FROM maven:latest AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM node:latest AS frontend
WORKDIR /app
COPY ./src/frontend/  ./
RUN npm install
RUN npm run build

FROM openjdk:latest
WORKDIR /app
COPY --from=builder /app/target/translator-0.0.1-SNAPSHOT.jar /app/translator.jar
COPY --from=frontend /app/dist /app
EXPOSE 8080
CMD ["java", "-jar", "translator.jar"]