FROM maven:latest AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:latest
WORKDIR /app
COPY --from=builder /app/target/translator-0.0.1-SNAPSHOT.jar /app/translator.jar
EXPOSE 5173
CMD ["java", "-jar", "translator.jar"]
