version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile-frontend
    ports:
      - "5173:80"
    networks:
      - app-network
        
networks:
  app-network:
    driver: bridge