FROM node:latest AS frontend-builder
WORKDIR /app
COPY ./src/frontend/ ./
RUN npm install
RUN npm run build

FROM maven:latest AS backend-builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:latest
WORKDIR /app
COPY --from=backend-builder /app/target/translator-0.0.1-SNAPSHOT.jar /app/translator.jar
COPY --from=frontend-builder /app/dist /app/dist
EXPOSE 8080 5173

CMD ["java", "-jar", "translator.jar"]
